services:
  server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SUPABASE_JDBC_URL=${SUPABASE_JDBC_URL}
      - SUPABASE_DB_USERNAME=${SUPABASE_DB_USERNAME}
      - SUPABASE_DB_PASSWORD=${SUPABASE_DB_PASSWORD}
    env_file:
      - .env
